language: java
# use Java 8
jdk:
- openjdk8

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2

branches:
    only:
    - master

deploy:
    provider: cloudfoundry
    api: https://api.system.eu01.cloud.schwarz
    username: Fabian.Kau@mail.schwarz
    password: Schwarz2020A
    organization: cf-training
    space: B6